name: Submit packaging

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'ISO date string to use in the action. Format YYYY-MM-DD'
        required: false
        default: ''

  schedule:
    - cron: '0 8 * * *'

jobs:
  nightly_packaging_submit:
    uses: ursacomputing/crossbow/.github/workflows/submit.yml@master
    with:
      report_type: packaging
      date: '${{ inputs.date }}'
    secrets:
      CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
